// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Session {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub preset: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tip_id: ::prost::alloc::string::String,
    #[prost(int32, tag="5")]
    pub max_turns: i32,
    #[prost(string, tag="6")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(int32, tag="7")]
    pub input_tokens: i32,
    #[prost(int32, tag="8")]
    pub output_tokens: i32,
    #[prost(int32, tag="9")]
    pub total_tokens: i32,
    #[prost(int32, tag="10")]
    pub last_input_tokens: i32,
    #[prost(int32, tag="11")]
    pub last_output_tokens: i32,
    #[prost(string, tag="12")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag="14")]
    pub last_used_at: ::prost::alloc::string::String,
    #[prost(string, tag="15")]
    pub locale: ::prost::alloc::string::String,
    #[prost(string, tag="16")]
    pub org: ::prost::alloc::string::String,
    #[prost(string, tag="17")]
    pub repo: ::prost::alloc::string::String,
    #[prost(string, tag="18")]
    pub branch: ::prost::alloc::string::String,
    #[prost(int32, tag="19")]
    pub unread_count: i32,
    #[prost(string, tag="20")]
    pub last_message_at: ::prost::alloc::string::String,
    #[prost(string, tag="21")]
    pub last_message_preview: ::prost::alloc::string::String,
    /// reasoning variant selected for this session (models.dev variant id).
    #[prost(string, tag="22")]
    pub variant: ::prost::alloc::string::String,
    /// monotonic per-session message counter (WatchSessions realtime list).
    #[prost(int32, tag="23")]
    pub message_seq: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub prev_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="5")]
    pub parts: ::prost::alloc::vec::Vec<Part>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Part {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub seq: i32,
    #[prost(string, tag="5")]
    pub data: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MailboxEntry {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub session_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub msg_type: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub payload: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub effective_at: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub consumed_at: ::prost::alloc::string::String,
    #[prost(int64, tag="9")]
    pub seq: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Preset {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub system_prompt_i18n: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="4")]
    pub tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag="5")]
    pub max_turns: i32,
    #[prost(bool, tag="6")]
    pub is_system: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provider {
    #[prost(string, tag="1")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub api_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="5")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, repeated, tag="6")]
    pub models: ::prost::alloc::vec::Vec<ProviderModel>,
    #[prost(string, tag="7")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProviderModel {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    /// required for non-gateway providers; 0 for gateway-classified kinds.
    #[prost(int64, tag="3")]
    pub context_limit: i64,
    /// text | image | video | speech | transcription | embedding | reranking.
    #[prost(string, tag="4")]
    pub model_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolInfo {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, optional, tag="4")]
    pub parameters: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, repeated, tag="5")]
    pub config_fields: ::prost::alloc::vec::Vec<ToolConfigField>,
    #[prost(string, repeated, tag="6")]
    pub required_config: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolConfigField {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub enum_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag="6")]
    pub default: ::core::option::Option<::prost_types::Value>,
    #[prost(string, tag="7")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub scope: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolConfig {
    #[prost(map="string, message", tag="1")]
    pub values: ::std::collections::HashMap<::prost::alloc::string::String, ::prost_types::Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptResponse {
    #[prost(string, tag="1")]
    pub event: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="2")]
    pub params: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub eid: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchSessionRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub since: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSessionResponse {
    #[prost(string, tag="1")]
    pub event: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub params: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, tag="3")]
    pub eid: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WatchSessionsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSessionsResponse {
    #[prost(message, repeated, tag="1")]
    pub upserts: ::prost::alloc::vec::Vec<Session>,
    #[prost(string, repeated, tag="2")]
    pub removed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="3")]
    pub snapshot: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileRef {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub mime: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub size: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListSessionsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsResponse {
    #[prost(message, repeated, tag="1")]
    pub sessions: ::prost::alloc::vec::Vec<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSessionRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub preset: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub org: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub repo: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub branch: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub variant: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateSessionResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub session_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSessionResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSessionResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListMessagesRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub limit: i32,
    #[prost(string, tag="3")]
    pub before: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub after: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMessagesResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(message, repeated, tag="2")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(bool, tag="3")]
    pub resync: bool,
    #[prost(string, tag="4")]
    pub tip_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub prompt: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub attachments: ::prost::alloc::vec::Vec<FileRef>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForkRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub preset: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ForkResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetModelRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub variant: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetModelResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UndoRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UndoResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateResponse {
    #[prost(message, optional, tag="1")]
    pub state: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MailboxRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailboxResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(message, repeated, tag="2")]
    pub mailbox: ::prost::alloc::vec::Vec<MailboxEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSettingsRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub preset: ::prost::alloc::string::String,
    #[prost(int32, optional, tag="4")]
    pub max_turns: ::core::option::Option<i32>,
    #[prost(string, tag="5")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub locale: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub variant: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateSettingsResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<Session>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterruptRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterruptResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(bool, tag="2")]
    pub interrupted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompactResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProvidersRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersResponse {
    #[prost(message, repeated, tag="1")]
    pub providers: ::prost::alloc::vec::Vec<Provider>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProvidersCatalogRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersCatalogResponse {
    #[prost(map="string, message", tag="1")]
    pub providers: ::std::collections::HashMap<::prost::alloc::string::String, CatalogProvider>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CatalogProvider {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub api: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub npm: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="5")]
    pub env: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map="string, message", tag="6")]
    pub models: ::std::collections::HashMap<::prost::alloc::string::String, ::prost_types::Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterProviderRequest {
    #[prost(message, optional, tag="1")]
    pub provider: ::core::option::Option<Provider>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterProviderResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoverGatewayModelsRequest {
    #[prost(string, tag="1")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub api_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="5")]
    pub headers: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DiscoverGatewayModelsResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub error: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub models: ::prost::alloc::vec::Vec<ProviderModel>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProviderRequest {
    #[prost(string, tag="1")]
    pub provider_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteProviderResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestProviderRequest {
    #[prost(string, tag="1")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub api_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub variant: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub capability: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TestProviderResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub result: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {
    #[prost(string, tag="1")]
    pub provider_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag="1")]
    pub models: ::prost::alloc::vec::Vec<ModelInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub variants: ::prost::alloc::vec::Vec<ModelVariant>,
    #[prost(int64, tag="4")]
    pub context_limit: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelVariant {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPresetsRequest {
    #[prost(string, tag="1")]
    pub locale: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPresetsResponse {
    #[prost(message, repeated, tag="1")]
    pub presets: ::prost::alloc::vec::Vec<Preset>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertPresetRequest {
    #[prost(message, optional, tag="1")]
    pub preset: ::core::option::Option<Preset>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpsertPresetResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePresetRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePresetResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreviewPresetRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PreviewPresetResponse {
    #[prost(string, tag="1")]
    pub template: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub rendered: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConfigRequest {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConfigResponse {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetConfigRequest {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetConfigResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListToolsRequest {
    #[prost(string, tag="1")]
    pub locale: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag="1")]
    pub tools: ::prost::alloc::vec::Vec<ToolInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetToolConfigRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetToolConfigResponse {
    #[prost(message, optional, tag="1")]
    pub config: ::core::option::Option<ToolConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetToolConfigRequest {
    #[prost(message, optional, tag="1")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetToolConfigResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetExtensionConfigRequest {
    #[prost(string, tag="1")]
    pub ext_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub value: ::core::option::Option<::prost_types::Value>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetExtensionConfigResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadFileRequest {
    #[prost(message, optional, tag="1")]
    pub file: ::core::option::Option<FileRef>,
    #[prost(string, tag="2")]
    pub data: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadFileResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestFileRequest {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub mime: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IngestFileResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileRequest {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileResponse {
    #[prost(bytes="vec", tag="1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub mime: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileMetaRequest {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileMetaResponse {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub mime: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub size: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetAgentConfigRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentConfigResponse {
    #[prost(message, optional, tag="1")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Tenant {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub disabled: bool,
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub updated_at: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TenantToken {
    #[prost(string, tag="1")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub last_used_at: ::prost::alloc::string::String,
    #[prost(bool, tag="6")]
    pub revoked: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTenantsRequest {
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantsResponse {
    #[prost(message, repeated, tag="1")]
    pub tenants: ::prost::alloc::vec::Vec<Tenant>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTenantRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateTenantResponse {
    #[prost(message, optional, tag="1")]
    pub tenant: ::core::option::Option<Tenant>,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTenantRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag="3")]
    pub disabled: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateTenantResponse {
    #[prost(message, optional, tag="1")]
    pub tenant: ::core::option::Option<Tenant>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTenantRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteTenantResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueTenantTokenRequest {
    #[prost(string, tag="1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IssueTenantTokenResponse {
    #[prost(message, optional, tag="1")]
    pub token: ::core::option::Option<TenantToken>,
    #[prost(string, tag="2")]
    pub plaintext: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListTenantTokensRequest {
    #[prost(string, tag="1")]
    pub tenant_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantTokensResponse {
    #[prost(message, repeated, tag="1")]
    pub tokens: ::prost::alloc::vec::Vec<TenantToken>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeTenantTokenRequest {
    #[prost(string, tag="1")]
    pub token_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeTenantTokenResponse {
    #[prost(bool, tag="1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateTenantTokenRequest {
    #[prost(string, tag="1")]
    pub token_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RotateTenantTokenResponse {
    #[prost(message, optional, tag="1")]
    pub token: ::core::option::Option<TenantToken>,
    #[prost(string, tag="2")]
    pub plaintext: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
