// This file is @generated by prost-build.
/// Session is a row in the agent session table.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Canonical model reference "provider_id/model_id". A bare model id is
    /// never resolved by flat lookup: the provider must be named explicitly.
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub preset: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tip_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub max_turns: i32,
    #[prost(string, tag = "6")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(int32, tag = "7")]
    pub input_tokens: i32,
    #[prost(int32, tag = "8")]
    pub output_tokens: i32,
    #[prost(int32, tag = "9")]
    pub total_tokens: i32,
    #[prost(int32, tag = "10")]
    pub last_input_tokens: i32,
    #[prost(int32, tag = "11")]
    pub last_output_tokens: i32,
    #[prost(string, tag = "12")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub updated_at: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub last_used_at: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub locale: ::prost::alloc::string::String,
    /// UI aggregates.
    #[prost(string, tag = "16")]
    pub org: ::prost::alloc::string::String,
    #[prost(string, tag = "17")]
    pub repo: ::prost::alloc::string::String,
    #[prost(string, tag = "18")]
    pub branch: ::prost::alloc::string::String,
    #[prost(int32, tag = "19")]
    pub unread_count: i32,
    #[prost(string, tag = "20")]
    pub last_message_at: ::prost::alloc::string::String,
    #[prost(string, tag = "21")]
    pub last_message_preview: ::prost::alloc::string::String,
    /// Selected reasoning variant id (e.g. "low"/"medium"/"high"/"max"/"fast").
    /// Empty means "no variant" (provider defaults; no providerOptions sent).
    #[prost(string, tag = "22")]
    pub variant: ::prost::alloc::string::String,
    /// Monotonic per-session message counter, bumped for every appended message
    /// (user/assistant/event/compaction). Clients derive the unread count as the
    /// number of messages with seq greater than their locally-persisted read
    /// watermark (read state is client-local; the agent never stores it).
    #[prost(int32, tag = "23")]
    pub message_seq: i32,
    /// Generic grouping key for a session (free-form, tenant-scoped). Empty =
    /// ungrouped. A subsession records its parent's session name here, but the
    /// field is deliberately generic: any client may group sessions arbitrarily
    /// (project, workspace, task…). Not validated against an enum.
    #[prost(string, tag = "24")]
    pub group: ::prost::alloc::string::String,
}
impl ::prost::Name for Session {
    const NAME: &'static str = "Session";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Session".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Session".into()
    }
}
/// Message row (bare).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub prev_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub parts: ::prost::alloc::vec::Vec<Part>,
}
impl ::prost::Name for Message {
    const NAME: &'static str = "Message";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Message".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Message".into()
    }
}
/// A tool/text part body. `data` is the JSON/plain payload.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Part {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub seq: i32,
    #[prost(string, tag = "5")]
    pub data: ::prost::alloc::string::String,
}
impl ::prost::Name for Part {
    const NAME: &'static str = "Part";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Part".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Part".into()
    }
}
/// Mailbox entry.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailboxEntry {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub msg_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub payload: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub effective_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub consumed_at: ::prost::alloc::string::String,
    #[prost(int64, tag = "9")]
    pub seq: i64,
}
impl ::prost::Name for MailboxEntry {
    const NAME: &'static str = "MailboxEntry";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.MailboxEntry".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.MailboxEntry".into()
    }
}
/// Preset row.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Preset {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub system_prompt_i18n: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub max_turns: i32,
    #[prost(bool, tag = "6")]
    pub is_system: bool,
}
impl ::prost::Name for Preset {
    const NAME: &'static str = "Preset";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Preset".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Preset".into()
    }
}
/// Provider row. A provider serves EXACTLY ONE modality (`capability`): its
/// models all share that capability. A host that serves several modalities is
/// registered once per modality (semantic grouping), so a modality's model
/// picker is simply "the models of that modality's providers".
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provider {
    #[prost(string, tag = "1")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub api_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub headers: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "6")]
    pub models: ::prost::alloc::vec::Vec<ProviderModel>,
    #[prost(string, tag = "7")]
    pub updated_at: ::prost::alloc::string::String,
    /// The single modality this provider serves (text | image | video | speech |
    /// transcription | embedding | rerank | realtime). New field (no renumber).
    #[prost(string, tag = "8")]
    pub capability: ::prost::alloc::string::String,
}
impl ::prost::Name for Provider {
    const NAME: &'static str = "Provider";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Provider".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Provider".into()
    }
}
/// Provider model entry. All of a provider's models share the provider's
/// `capability`; `model_type` mirrors it (kept for wire compatibility and for
/// clients that read the model directly).
///
///    - text      -> context_limit (> 0) REQUIRED (drives compaction budgets)
///    - non-text  -> context_limit MUST be 0 (not a chat model)
///
/// A provider protocol may serve any modality its wire format supports
/// (validated server-side against the capability matrix — see
/// ListProvidersCatalog). There is no gateway special-casing.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProviderModel {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub context_limit: i64,
    /// The model's modality, identical to its provider's `capability`.
    #[prost(string, tag = "4")]
    pub model_type: ::prost::alloc::string::String,
}
impl ::prost::Name for ProviderModel {
    const NAME: &'static str = "ProviderModel";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ProviderModel".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ProviderModel".into()
    }
}
/// Tool discovery entry.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub category: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub parameters: ::core::option::Option<::prost_types::Struct>,
    #[prost(message, repeated, tag = "5")]
    pub config_fields: ::prost::alloc::vec::Vec<ToolConfigField>,
    #[prost(string, repeated, tag = "6")]
    pub required_config: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for ToolInfo {
    const NAME: &'static str = "ToolInfo";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ToolInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ToolInfo".into()
    }
}
/// Declared config knob for a tool/extension.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolConfigField {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub enum_values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub default: ::core::option::Option<::prost_types::Value>,
    #[prost(string, tag = "7")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub scope: ::prost::alloc::string::String,
    /// Semantic kind: "value" (default, an ordinary knob) or "model" (the value
    /// is a `provider_id/model_id` reference; the client renders a picker scoped
    /// to `capability` against the provider registry instead of a text field).
    #[prost(string, tag = "9")]
    pub kind: ::prost::alloc::string::String,
    /// Required when `kind == "model"`: the modality the reference must match
    /// (text | image | video | speech | transcription | embedding | rerank |
    /// realtime).
    #[prost(string, tag = "10")]
    pub capability: ::prost::alloc::string::String,
}
impl ::prost::Name for ToolConfigField {
    const NAME: &'static str = "ToolConfigField";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ToolConfigField".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ToolConfigField".into()
    }
}
/// A tool's configured value.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolConfig {
    #[prost(map = "string, message", tag = "1")]
    pub values: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost_types::Value,
    >,
}
impl ::prost::Name for ToolConfig {
    const NAME: &'static str = "ToolConfig";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ToolConfig".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ToolConfig".into()
    }
}
/// SSE-ish stream event emitted by Prompt streaming.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptResponse {
    /// status | text-delta | tool-call | tool-result | error | turn-complete
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "2")]
    pub params: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, tag = "3")]
    pub eid: ::prost::alloc::string::String,
}
impl ::prost::Name for PromptResponse {
    const NAME: &'static str = "PromptResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.PromptResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.PromptResponse".into()
    }
}
/// WatchSession streams live session events (the Connect replacement for the
/// SSE /stream endpoint): turn deltas, tool calls, errors and completions.
/// `since` is a message id ANCHOR for incremental replay: when set, a replay
/// starts AFTER that message (so a client that was offline still catches the
/// turns that completed meanwhile). Empty = live-from-now (or the active run).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSessionRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub since: ::prost::alloc::string::String,
}
impl ::prost::Name for WatchSessionRequest {
    const NAME: &'static str = "WatchSessionRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.WatchSessionRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.WatchSessionRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSessionResponse {
    #[prost(string, tag = "1")]
    pub event: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, tag = "3")]
    pub eid: ::prost::alloc::string::String,
}
impl ::prost::Name for WatchSessionResponse {
    const NAME: &'static str = "WatchSessionResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.WatchSessionResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.WatchSessionResponse".into()
    }
}
/// WatchSessions streams the session list in real time: an initial full
/// snapshot, then per-session upserts (message-fact changes, settings changes)
/// and removals (deletes). Replaces list polling.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WatchSessionsRequest {}
impl ::prost::Name for WatchSessionsRequest {
    const NAME: &'static str = "WatchSessionsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.WatchSessionsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.WatchSessionsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WatchSessionsResponse {
    /// New/updated session snapshots (message facts + settings).
    #[prost(message, repeated, tag = "1")]
    pub upserts: ::prost::alloc::vec::Vec<Session>,
    /// Session names that were removed.
    #[prost(string, repeated, tag = "2")]
    pub removed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// True for the initial full snapshot: the client replaces its whole list
    /// with `upserts` (dropping anything not present) instead of merging.
    #[prost(bool, tag = "3")]
    pub snapshot: bool,
}
impl ::prost::Name for WatchSessionsResponse {
    const NAME: &'static str = "WatchSessionsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.WatchSessionsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.WatchSessionsResponse".into()
    }
}
/// A file reference (attachment).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileRef {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub size: i32,
}
impl ::prost::Name for FileRef {
    const NAME: &'static str = "FileRef";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.FileRef".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.FileRef".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListSessionsRequest {}
impl ::prost::Name for ListSessionsRequest {
    const NAME: &'static str = "ListSessionsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListSessionsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListSessionsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSessionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<Session>,
}
impl ::prost::Name for ListSessionsResponse {
    const NAME: &'static str = "ListSessionsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListSessionsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListSessionsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSessionRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Canonical model reference "provider_id/model_id".
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub preset: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub org: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub repo: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub branch: ::prost::alloc::string::String,
    /// Optional reasoning variant id (see ModelInfo.variants).
    #[prost(string, tag = "7")]
    pub variant: ::prost::alloc::string::String,
    /// Optional generic grouping key (empty = ungrouped). A subsession sets this
    /// to its parent session name.
    #[prost(string, tag = "8")]
    pub group: ::prost::alloc::string::String,
}
impl ::prost::Name for CreateSessionRequest {
    const NAME: &'static str = "CreateSessionRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CreateSessionRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CreateSessionRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSessionResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub session_name: ::prost::alloc::string::String,
}
impl ::prost::Name for CreateSessionResponse {
    const NAME: &'static str = "CreateSessionResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CreateSessionResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CreateSessionResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for GetSessionRequest {
    const NAME: &'static str = "GetSessionRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetSessionRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetSessionRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for GetSessionResponse {
    const NAME: &'static str = "GetSessionResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetSessionResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetSessionResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteSessionRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for DeleteSessionRequest {
    const NAME: &'static str = "DeleteSessionRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteSessionRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteSessionRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteSessionResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for DeleteSessionResponse {
    const NAME: &'static str = "DeleteSessionResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteSessionResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteSessionResponse".into()
    }
}
/// ListMessages reads a session's message chain. Two modes:
///    * ANCHORED / incremental: `after` is a message id ANCHOR (a pin) the
///      client already has. The response is the chain segment AFTER it, i.e. the
///      walk from the current tip back to (excluding) that anchor — the messages
///      appended since the client last synced. If the anchor is NOT on the
///      current chain (it was withdrawn via undo, or the chain was forked), the
///      response sets `resync=true` and the client must drop its cache and
///      re-fetch. `tip_id` always echoes the current tip so the client can store
///      it as the next anchor.
///    * BACKWARD paging (existing): with `before` set (and `after` empty) the
///      chain is read oldest→newest for `limit` messages BEFORE that cursor;
///      with neither set, the newest `limit` messages.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMessagesRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// Backward-paging cursor (exclusive): return messages before this id.
    #[prost(string, tag = "3")]
    pub before: ::prost::alloc::string::String,
    /// Incremental anchor (exclusive): return messages after this id. When the
    /// anchor is absent from the current chain, the server signals `resync`.
    #[prost(string, tag = "4")]
    pub after: ::prost::alloc::string::String,
}
impl ::prost::Name for ListMessagesRequest {
    const NAME: &'static str = "ListMessagesRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListMessagesRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListMessagesRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListMessagesResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    /// The anchor was not on the current chain (withdrawn/forked): the client
    /// must discard its local copy of this session and re-fetch from scratch.
    #[prost(bool, tag = "3")]
    pub resync: bool,
    /// Current chain tip id (store as the next `after` anchor).
    #[prost(string, tag = "4")]
    pub tip_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ListMessagesResponse {
    const NAME: &'static str = "ListMessagesResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListMessagesResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListMessagesResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub prompt: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub attachments: ::prost::alloc::vec::Vec<FileRef>,
}
impl ::prost::Name for PromptRequest {
    const NAME: &'static str = "PromptRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.PromptRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.PromptRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForkRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub preset: ::prost::alloc::string::String,
}
impl ::prost::Name for ForkRequest {
    const NAME: &'static str = "ForkRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ForkRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ForkRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForkResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for ForkResponse {
    const NAME: &'static str = "ForkResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ForkResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ForkResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for RenameRequest {
    const NAME: &'static str = "RenameRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RenameRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RenameRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenameResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for RenameResponse {
    const NAME: &'static str = "RenameResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RenameResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RenameResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetModelRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub variant: ::prost::alloc::string::String,
}
impl ::prost::Name for SetModelRequest {
    const NAME: &'static str = "SetModelRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetModelRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetModelRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetModelResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for SetModelResponse {
    const NAME: &'static str = "SetModelResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetModelResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetModelResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UndoRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
impl ::prost::Name for UndoRequest {
    const NAME: &'static str = "UndoRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UndoRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UndoRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UndoResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for UndoResponse {
    const NAME: &'static str = "UndoResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UndoResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UndoResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for StateRequest {
    const NAME: &'static str = "StateRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.StateRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.StateRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StateResponse {
    #[prost(message, optional, tag = "1")]
    pub state: ::core::option::Option<::prost_types::Struct>,
}
impl ::prost::Name for StateResponse {
    const NAME: &'static str = "StateResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.StateResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.StateResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailboxRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for MailboxRequest {
    const NAME: &'static str = "MailboxRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.MailboxRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.MailboxRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MailboxResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(message, repeated, tag = "2")]
    pub mailbox: ::prost::alloc::vec::Vec<MailboxEntry>,
}
impl ::prost::Name for MailboxResponse {
    const NAME: &'static str = "MailboxResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.MailboxResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.MailboxResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSettingsRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub preset: ::prost::alloc::string::String,
    /// Optional: omitted means "inherit (preset / default)"; an explicit value
    /// must be > 0 (0 is rejected).
    #[prost(int32, optional, tag = "4")]
    pub max_turns: ::core::option::Option<i32>,
    #[prost(string, tag = "5")]
    pub system_prompt: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub locale: ::prost::alloc::string::String,
    /// Selected reasoning variant id (empty clears it).
    #[prost(string, tag = "7")]
    pub variant: ::prost::alloc::string::String,
    /// Generic grouping key (empty clears it). Included for completeness; the
    /// subsession flow sets it at creation time.
    #[prost(string, optional, tag = "8")]
    pub group: ::core::option::Option<::prost::alloc::string::String>,
}
impl ::prost::Name for UpdateSettingsRequest {
    const NAME: &'static str = "UpdateSettingsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpdateSettingsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpdateSettingsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSettingsResponse {
    #[prost(message, optional, tag = "1")]
    pub session: ::core::option::Option<Session>,
}
impl ::prost::Name for UpdateSettingsResponse {
    const NAME: &'static str = "UpdateSettingsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpdateSettingsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpdateSettingsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InterruptRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for InterruptRequest {
    const NAME: &'static str = "InterruptRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.InterruptRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.InterruptRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct InterruptResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(bool, tag = "2")]
    pub interrupted: bool,
}
impl ::prost::Name for InterruptResponse {
    const NAME: &'static str = "InterruptResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.InterruptResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.InterruptResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompactRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for CompactRequest {
    const NAME: &'static str = "CompactRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CompactRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CompactRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CompactResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for CompactResponse {
    const NAME: &'static str = "CompactResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CompactResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CompactResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListProvidersRequest {}
impl ::prost::Name for ListProvidersRequest {
    const NAME: &'static str = "ListProvidersRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListProvidersRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListProvidersRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersResponse {
    #[prost(message, repeated, tag = "1")]
    pub providers: ::prost::alloc::vec::Vec<Provider>,
}
impl ::prost::Name for ListProvidersResponse {
    const NAME: &'static str = "ListProvidersResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListProvidersResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListProvidersResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListProvidersCatalogRequest {}
impl ::prost::Name for ListProvidersCatalogRequest {
    const NAME: &'static str = "ListProvidersCatalogRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListProvidersCatalogRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListProvidersCatalogRequest".into()
    }
}
/// The registration catalog: every provider api type the server accepts and
/// the model capabilities each can serve. Single source of truth for client
/// registration forms — clients fetch this instead of hardcoding the matrix
/// (with a bundled fallback copy for offline use).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProvidersCatalogResponse {
    /// api type id (e.g. "openai-compatible") -> its catalog entry.
    #[prost(map = "string, message", tag = "1")]
    pub api_types: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ApiTypeCatalog,
    >,
}
impl ::prost::Name for ListProvidersCatalogResponse {
    const NAME: &'static str = "ListProvidersCatalogResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListProvidersCatalogResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListProvidersCatalogResponse".into()
    }
}
/// Catalog entry for one provider api type.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApiTypeCatalog {
    /// Capability tags a model of this api type may declare in `model_type`
    /// (text | image | video | speech | transcription | embedding | rerank).
    #[prost(string, repeated, tag = "1")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for ApiTypeCatalog {
    const NAME: &'static str = "ApiTypeCatalog";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ApiTypeCatalog".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ApiTypeCatalog".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterProviderRequest {
    #[prost(message, optional, tag = "1")]
    pub provider: ::core::option::Option<Provider>,
}
impl ::prost::Name for RegisterProviderRequest {
    const NAME: &'static str = "RegisterProviderRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RegisterProviderRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RegisterProviderRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RegisterProviderResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for RegisterProviderResponse {
    const NAME: &'static str = "RegisterProviderResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RegisterProviderResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RegisterProviderResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteProviderRequest {
    #[prost(string, tag = "1")]
    pub provider_id: ::prost::alloc::string::String,
}
impl ::prost::Name for DeleteProviderRequest {
    const NAME: &'static str = "DeleteProviderRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteProviderRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteProviderRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteProviderResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for DeleteProviderResponse {
    const NAME: &'static str = "DeleteProviderResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteProviderResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteProviderResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestProviderRequest {
    #[prost(string, tag = "1")]
    pub provider_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub api_type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub base_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub api_key: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub model: ::prost::alloc::string::String,
    /// Optional reasoning variant id to exercise in the test generation.
    #[prost(string, tag = "6")]
    pub variant: ::prost::alloc::string::String,
    /// What the model under test generates: "text" (default). Only text models
    /// are testable today; image/video/speech are rejected with a clear message.
    #[prost(string, tag = "7")]
    pub capability: ::prost::alloc::string::String,
}
impl ::prost::Name for TestProviderRequest {
    const NAME: &'static str = "TestProviderRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.TestProviderRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.TestProviderRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestProviderResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub result: ::prost::alloc::string::String,
}
impl ::prost::Name for TestProviderResponse {
    const NAME: &'static str = "TestProviderResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.TestProviderResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.TestProviderResponse".into()
    }
}
/// ListModels returns the models of ONE provider. provider_id is required: the
/// server rejects an empty value (InvalidArgument) so a global flat model list
/// — which would surface duplicate ids across providers — is never produced.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsRequest {
    #[prost(string, tag = "1")]
    pub provider_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ListModelsRequest {
    const NAME: &'static str = "ListModelsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListModelsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListModelsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<ModelInfo>,
}
impl ::prost::Name for ListModelsResponse {
    const NAME: &'static str = "ListModelsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListModelsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListModelsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Reasoning variants offered by this model (from the models.dev catalog).
    /// Empty when the model has no reasoning options or is not in the catalog.
    #[prost(message, repeated, tag = "3")]
    pub variants: ::prost::alloc::vec::Vec<ModelVariant>,
    /// Context window (tokens) configured for this provider model.
    #[prost(int64, tag = "4")]
    pub context_limit: i64,
}
impl ::prost::Name for ModelInfo {
    const NAME: &'static str = "ModelInfo";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ModelInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ModelInfo".into()
    }
}
/// A selectable reasoning variant for a model (e.g. low/medium/high/max, or a
/// fast mode). `id` is passed back on CreateSession/SetModel/UpdateSettings.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelVariant {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
impl ::prost::Name for ModelVariant {
    const NAME: &'static str = "ModelVariant";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ModelVariant".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ModelVariant".into()
    }
}
/// ListPresets lists presets. When locale is set (e.g. "zh"), each preset's
/// system_prompt is resolved from its i18n map for that locale, falling back
/// to the default prompt.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPresetsRequest {
    #[prost(string, tag = "1")]
    pub locale: ::prost::alloc::string::String,
}
impl ::prost::Name for ListPresetsRequest {
    const NAME: &'static str = "ListPresetsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListPresetsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListPresetsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPresetsResponse {
    #[prost(message, repeated, tag = "1")]
    pub presets: ::prost::alloc::vec::Vec<Preset>,
}
impl ::prost::Name for ListPresetsResponse {
    const NAME: &'static str = "ListPresetsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListPresetsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListPresetsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpsertPresetRequest {
    #[prost(message, optional, tag = "1")]
    pub preset: ::core::option::Option<Preset>,
}
impl ::prost::Name for UpsertPresetRequest {
    const NAME: &'static str = "UpsertPresetRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpsertPresetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpsertPresetRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpsertPresetResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for UpsertPresetResponse {
    const NAME: &'static str = "UpsertPresetResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpsertPresetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpsertPresetResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeletePresetRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for DeletePresetRequest {
    const NAME: &'static str = "DeletePresetRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeletePresetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeletePresetRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeletePresetResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for DeletePresetResponse {
    const NAME: &'static str = "DeletePresetResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeletePresetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeletePresetResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreviewPresetRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for PreviewPresetRequest {
    const NAME: &'static str = "PreviewPresetRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.PreviewPresetRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.PreviewPresetRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PreviewPresetResponse {
    #[prost(string, tag = "1")]
    pub template: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub rendered: ::prost::alloc::string::String,
}
impl ::prost::Name for PreviewPresetResponse {
    const NAME: &'static str = "PreviewPresetResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.PreviewPresetResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.PreviewPresetResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConfigRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
}
impl ::prost::Name for GetConfigRequest {
    const NAME: &'static str = "GetConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetConfigRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConfigResponse {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
impl ::prost::Name for GetConfigResponse {
    const NAME: &'static str = "GetConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetConfigResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetConfigRequest {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
impl ::prost::Name for SetConfigRequest {
    const NAME: &'static str = "SetConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetConfigRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetConfigResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for SetConfigResponse {
    const NAME: &'static str = "SetConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetConfigResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsRequest {
    #[prost(string, tag = "1")]
    pub locale: ::prost::alloc::string::String,
}
impl ::prost::Name for ListToolsRequest {
    const NAME: &'static str = "ListToolsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListToolsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListToolsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListToolsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tools: ::prost::alloc::vec::Vec<ToolInfo>,
}
impl ::prost::Name for ListToolsResponse {
    const NAME: &'static str = "ListToolsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListToolsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListToolsResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetToolConfigRequest {}
impl ::prost::Name for GetToolConfigRequest {
    const NAME: &'static str = "GetToolConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetToolConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetToolConfigRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetToolConfigResponse {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<ToolConfig>,
}
impl ::prost::Name for GetToolConfigResponse {
    const NAME: &'static str = "GetToolConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetToolConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetToolConfigResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetToolConfigRequest {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
impl ::prost::Name for SetToolConfigRequest {
    const NAME: &'static str = "SetToolConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetToolConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetToolConfigRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetToolConfigResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for SetToolConfigResponse {
    const NAME: &'static str = "SetToolConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetToolConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetToolConfigResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetExtensionConfigRequest {
    #[prost(string, tag = "1")]
    pub ext_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<::prost_types::Value>,
}
impl ::prost::Name for SetExtensionConfigRequest {
    const NAME: &'static str = "SetExtensionConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetExtensionConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetExtensionConfigRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetExtensionConfigResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for SetExtensionConfigResponse {
    const NAME: &'static str = "SetExtensionConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.SetExtensionConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.SetExtensionConfigResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadFileRequest {
    #[prost(message, optional, tag = "1")]
    pub file: ::core::option::Option<FileRef>,
    #[prost(string, tag = "2")]
    pub data: ::prost::alloc::string::String,
}
impl ::prost::Name for UploadFileRequest {
    const NAME: &'static str = "UploadFileRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UploadFileRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UploadFileRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadFileResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
impl ::prost::Name for UploadFileResponse {
    const NAME: &'static str = "UploadFileResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UploadFileResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UploadFileResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestFileRequest {
    /// optional; empty => server mints one
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub mime: ::prost::alloc::string::String,
}
impl ::prost::Name for IngestFileRequest {
    const NAME: &'static str = "IngestFileRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.IngestFileRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.IngestFileRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestFileResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
impl ::prost::Name for IngestFileResponse {
    const NAME: &'static str = "IngestFileResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.IngestFileResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.IngestFileResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
impl ::prost::Name for GetFileRequest {
    const NAME: &'static str = "GetFileRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetFileRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetFileRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime: ::prost::alloc::string::String,
}
impl ::prost::Name for GetFileResponse {
    const NAME: &'static str = "GetFileResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetFileResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetFileResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileMetaRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
impl ::prost::Name for GetFileMetaRequest {
    const NAME: &'static str = "GetFileMetaRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetFileMetaRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetFileMetaRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetFileMetaResponse {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub mime: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub size: i32,
}
impl ::prost::Name for GetFileMetaResponse {
    const NAME: &'static str = "GetFileMetaResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetFileMetaResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetFileMetaResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetAgentConfigRequest {}
impl ::prost::Name for GetAgentConfigRequest {
    const NAME: &'static str = "GetAgentConfigRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetAgentConfigRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetAgentConfigRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAgentConfigResponse {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<::prost_types::Struct>,
}
impl ::prost::Name for GetAgentConfigResponse {
    const NAME: &'static str = "GetAgentConfigResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.GetAgentConfigResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.GetAgentConfigResponse".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
impl ::prost::Name for HealthRequest {
    const NAME: &'static str = "HealthRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.HealthRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.HealthRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for HealthResponse {
    const NAME: &'static str = "HealthResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.HealthResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.HealthResponse".into()
    }
}
/// Tenant is one isolation domain. `id` is the plaintext isolation key used on
/// the wire (abc.<id>.<...>) and in the database.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tenant {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// A disabled tenant's tokens stop authenticating (fail-closed); its data is
    /// retained. Re-enable by clearing this flag.
    #[prost(bool, tag = "3")]
    pub disabled: bool,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub updated_at: ::prost::alloc::string::String,
}
impl ::prost::Name for Tenant {
    const NAME: &'static str = "Tenant";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.Tenant".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.Tenant".into()
    }
}
/// TenantToken is a bearer credential minted for one tenant. The plaintext is
/// returned ONLY at issue/rotate time; the server stores just its sha256.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TenantToken {
    #[prost(string, tag = "1")]
    pub token_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub last_used_at: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub revoked: bool,
}
impl ::prost::Name for TenantToken {
    const NAME: &'static str = "TenantToken";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.TenantToken".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.TenantToken".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListTenantsRequest {}
impl ::prost::Name for ListTenantsRequest {
    const NAME: &'static str = "ListTenantsRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListTenantsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListTenantsRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantsResponse {
    #[prost(message, repeated, tag = "1")]
    pub tenants: ::prost::alloc::vec::Vec<Tenant>,
}
impl ::prost::Name for ListTenantsResponse {
    const NAME: &'static str = "ListTenantsResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListTenantsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListTenantsResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTenantRequest {
    /// Plaintext tenant id: ^\[A-Za-z0-9_-\]{1,64}$.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
impl ::prost::Name for CreateTenantRequest {
    const NAME: &'static str = "CreateTenantRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CreateTenantRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CreateTenantRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTenantResponse {
    #[prost(message, optional, tag = "1")]
    pub tenant: ::core::option::Option<Tenant>,
    /// The bootstrap token minted for the new tenant (plaintext, shown once).
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
impl ::prost::Name for CreateTenantResponse {
    const NAME: &'static str = "CreateTenantResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.CreateTenantResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.CreateTenantResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTenantRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "3")]
    pub disabled: ::core::option::Option<bool>,
}
impl ::prost::Name for UpdateTenantRequest {
    const NAME: &'static str = "UpdateTenantRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpdateTenantRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpdateTenantRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateTenantResponse {
    #[prost(message, optional, tag = "1")]
    pub tenant: ::core::option::Option<Tenant>,
}
impl ::prost::Name for UpdateTenantResponse {
    const NAME: &'static str = "UpdateTenantResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.UpdateTenantResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.UpdateTenantResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteTenantRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
impl ::prost::Name for DeleteTenantRequest {
    const NAME: &'static str = "DeleteTenantRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteTenantRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteTenantRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteTenantResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for DeleteTenantResponse {
    const NAME: &'static str = "DeleteTenantResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.DeleteTenantResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.DeleteTenantResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IssueTenantTokenRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub label: ::prost::alloc::string::String,
}
impl ::prost::Name for IssueTenantTokenRequest {
    const NAME: &'static str = "IssueTenantTokenRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.IssueTenantTokenRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.IssueTenantTokenRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IssueTenantTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub token: ::core::option::Option<TenantToken>,
    /// The plaintext token (shown once; never retrievable again).
    #[prost(string, tag = "2")]
    pub plaintext: ::prost::alloc::string::String,
}
impl ::prost::Name for IssueTenantTokenResponse {
    const NAME: &'static str = "IssueTenantTokenResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.IssueTenantTokenResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.IssueTenantTokenResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantTokensRequest {
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
}
impl ::prost::Name for ListTenantTokensRequest {
    const NAME: &'static str = "ListTenantTokensRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListTenantTokensRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListTenantTokensRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListTenantTokensResponse {
    #[prost(message, repeated, tag = "1")]
    pub tokens: ::prost::alloc::vec::Vec<TenantToken>,
}
impl ::prost::Name for ListTenantTokensResponse {
    const NAME: &'static str = "ListTenantTokensResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.ListTenantTokensResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.ListTenantTokensResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeTenantTokenRequest {
    #[prost(string, tag = "1")]
    pub token_id: ::prost::alloc::string::String,
}
impl ::prost::Name for RevokeTenantTokenRequest {
    const NAME: &'static str = "RevokeTenantTokenRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RevokeTenantTokenRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RevokeTenantTokenRequest".into()
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RevokeTenantTokenResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
impl ::prost::Name for RevokeTenantTokenResponse {
    const NAME: &'static str = "RevokeTenantTokenResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RevokeTenantTokenResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RevokeTenantTokenResponse".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RotateTenantTokenRequest {
    #[prost(string, tag = "1")]
    pub token_id: ::prost::alloc::string::String,
}
impl ::prost::Name for RotateTenantTokenRequest {
    const NAME: &'static str = "RotateTenantTokenRequest";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RotateTenantTokenRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RotateTenantTokenRequest".into()
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RotateTenantTokenResponse {
    #[prost(message, optional, tag = "1")]
    pub token: ::core::option::Option<TenantToken>,
    /// The new plaintext token (shown once).
    #[prost(string, tag = "2")]
    pub plaintext: ::prost::alloc::string::String,
}
impl ::prost::Name for RotateTenantTokenResponse {
    const NAME: &'static str = "RotateTenantTokenResponse";
    const PACKAGE: &'static str = "agent.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "agent.v1.RotateTenantTokenResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/agent.v1.RotateTenantTokenResponse".into()
    }
}
